added endpoint for fetching servicenow tables
takipi/api-spec pull request #62
Opened 2019-05-07 09:35 UTC by jenjenp

2019-05-07 10:45 UTC, noammat requested changes

2019-05-07 10:45 UTC, noammat commented on services.yaml
> +                type: array
The response is an array of an object of a `ServiceNow Table` which contains the table's display name (dubbed as label) and the table's internal name (dubbed as name and is also the table's ID)

2019-05-13 07:10 UTC, chook commented on services.yaml
> +                example: "pa$$1"
Passi? :D

2019-05-13 07:14 UTC, jenjenp commented on services.yaml
> +                example: "pa$$1"
lol

2019-05-21 07:03 UTC, noammat approved these changes

2019-07-17 14:25 UTC, merged