added a query param to the agent status report
takipi/api-spec pull request #74
Opened 2019-11-14 22:05 UTC by jenjenp

2019-11-14 22:08 UTC, chook requested changes

2019-11-14 22:08 UTC, chook commented on services.yaml
> +        - in: query
also exists in the full and collectors

2019-11-17 08:46 UTC, jenjenp commented on services.yaml
> +        - in: query
fixed

2019-11-26 23:41 UTC, chook approved these changes

2019-12-18 08:55 UTC, merged