updated agent batch update endpoint to support single agent update
takipi/api-spec pull request #77
Opened 2020-02-24 09:40 UTC by jenjenp

2020-02-24 18:09 UTC, chook reviewed
I am not used to seeing markup in our yaml file - is it really needed?

2020-03-17 08:50 UTC, KaminerD requested changes

2020-03-17 08:50 UTC, KaminerD commented on services.yaml
> +          description: Agent IDs added to the filter. The update will apply only to selected agent IDs. NOTE - _The filter should contain *at least* one server, application or agent._
same goes here:
The update will apply to all existing and future agents in the selected application/s.

2020-03-23 08:36 UTC, KaminerD approved these changes

2020-03-23 16:49 UTC, merged